In [1]:
import numpy as np

In [2]:
import time
import sys 

Print size of List and numpy array

In [7]:
#list
l = range(1000)
print(sys.getsizeof(5)*len(l)) #size of one integer * number of items

#numpy array
a = np.arange(1000) #"arange" used to store numbers from 0 to "num"
print(a.size*a.itemsize)

28000
4000


Adding two corresponding lists and np arrays

In [13]:
size = 10000000

l1 = range(size)
l2 = range(size)

a1 = np.arange(size)
a2 = np.arange(size)

In [14]:
#adding corresponding lists

start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print((time.time()-start)*1000)

626.9533634185791


In [15]:
start = time.time()
result=a1+a2
print((time.time()-start)*1000)

119.82393264770508


In [16]:
a=np.array([1,2,3])

In [21]:
print(a[0])
print(a[2])

1
3


2D array

In [32]:
a = np.array([[1,2],[3,4],[3,5],[6,4]])
print(a.ndim)

2


In [33]:
a

array([[1, 2],
       [3, 4],
       [3, 5],
       [6, 4]])

In [27]:
#integers
print(a.itemsize)
print(a.dtype)

4
int32


In [30]:
a = np.array([[1,2],[3,4],[3,5],[6,4]], dtype = np.float64)
a.dtype


dtype('float64')

In [31]:
a

array([[1., 2.],
       [3., 4.],
       [3., 5.],
       [6., 4.]])

In [34]:
a.shape

(4, 2)

All zeros array

In [35]:
arr = np.zeros ((3,4), dtype = np.int32)

In [36]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [37]:
#by defaut it creates float datatype
arr =np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

arange() function in numpy array

In [39]:
a = np.arange(5) #stores nos. from 0 to 4
a

array([0, 1, 2, 3, 4])

In [41]:
a = np.arange(2,5) #stores nos. from 2 to 5
a

array([2, 3, 4])

In [42]:
a = np.arange(1,6,2) #stores nos. from 1 to 5 with increment of 2
a


array([1, 3, 5])

linspace

In [43]:
a = np.linspace(1,5,10) # to generate 10 linearly sequenced numbers between 1 to 5
a

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

Reshaping

In [54]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
a #a is not changed yet.. it is as it is

array([[1, 2],
       [3, 4],
       [5, 6]])

ravel sunction to flatten your array

In [57]:
a.ravel() #to make an array to 1D

array([1, 2, 3, 4, 5, 6])

In [58]:
a #a is not changed yet.. it is as it is

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
print(a.min())

1


In [60]:
print(a.max())

6


In [61]:
a.sum() #to add all numbers of n array

21

using axis in sum

In [62]:
#axis=0 means - top to bottom
#axis =1 means - left to right
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
print("Sum of Axis = 0 : ", a.sum(axis=0))
print()
print("Sum of Axis = 1 : ", a.sum(axis=1))

Sum of Axis = 0 :  [ 9 12]

Sum of Axis = 1 :  [ 3  7 11]


To find square root of an array

In [68]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

Standard Deviation

In [69]:
np.std(a)

1.707825127659933